name: Create a sentry release on a github release creation

on:
  release:
    types: created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_ORG: veryfyodor
      SENTRY_PROJECT: cbrwizard
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - run: curl -sL https://sentry.io/get-cli/ | bash
      - run: sentry-cli releases new -p ${{ env.SENTRY_PROJECT }} ${{ github.event.release.tag_name }}
      - run: sentry-cli releases set-commits --auto ${{ github.event.release.tag_name }}
      - run: npm install
      - run: npm run build
      - run: sentry-cli releases files ${{ github.event.release.tag_name }} upload-sourcemaps build/static/js --url-prefix '~/static/js' --rewrite
      - run: sentry-cli releases deploys ${{ github.event.release.tag_name }} new -e staging
      - run: sentry-cli releases deploys ${{ github.event.release.tag_name }} new -e production
      - run: sentry-cli releases finalize ${{ github.event.release.tag_name }}
