name: Create & deploy a Sentry release on a new github release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Sentry release
        uses: cbrwizard/sentry-release-github-action
        with:
          release: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
